package marmot.script.command

import marmot.*;
import marmot.type.*;
import marmot.script.*;
import marmot.optor.*;
import static marmot.optor.AggregateFunction.*;


def methodMissing(String name, args) {
	CommandScriptParser parser = new CommandScriptParser(marmot, MARMOT_VERBOSE);
	Closure script = (Closure)args[0]
	script.delegate = parser
	script.resolveStrategy = Closure.DELEGATE_ONLY;
	script()
}